# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputHeater.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 537)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/heater.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radioButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_5.setStyleSheet("QRadioButton::radioButton_5 {\n"
"text-align: right;\n"
"}")
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_32 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.label_26 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.lineEdit_24 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_3.addWidget(self.lineEdit_24)
        self.label_28 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_3.addWidget(self.label_28)
        self.lineEdit_28 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_3.addWidget(self.lineEdit_28)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_29 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout.addWidget(self.label_30)
        self.label_19 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout.addWidget(self.lineEdit_19)
        self.label_23 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout.addWidget(self.lineEdit_22)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_25 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.lineEdit_27 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_4.addWidget(self.lineEdit_27)
        self.label_27 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.lineEdit_25 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout_4.addWidget(self.lineEdit_25)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setAutoFillBackground(True)
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setAutoRepeat(False)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_20 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_2.addWidget(self.lineEdit_20)
        self.label_24 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(9)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_2.addWidget(self.lineEdit_23)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_19, self.lineEdit_22)
        Form.setTabOrder(self.lineEdit_22, self.radioButton_2)
        Form.setTabOrder(self.radioButton_2, self.lineEdit_20)
        Form.setTabOrder(self.lineEdit_20, self.lineEdit_23)
        Form.setTabOrder(self.lineEdit_23, self.radioButton_5)
        Form.setTabOrder(self.radioButton_5, self.lineEdit_24)
        Form.setTabOrder(self.lineEdit_24, self.lineEdit_28)
        Form.setTabOrder(self.lineEdit_28, self.radioButton_4)
        Form.setTabOrder(self.radioButton_4, self.lineEdit_27)
        Form.setTabOrder(self.lineEdit_27, self.lineEdit_25)
        Form.setTabOrder(self.lineEdit_25, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.pushButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "اطلاعات گرم کن ایستگاه تقلیل فشار گاز"))
        self.radioButton_5.setText(_translate("Form", "گرم کن دو"))
        self.label_32.setText(_translate("Form", "مشعل یک :"))
        self.label_26.setText(_translate("Form", "دمای دودکش (C°):"))
        self.lineEdit_24.setPlaceholderText(_translate("Form", "ex: 200 (°C)"))
        self.label_28.setText(_translate("Form", "درصد اکسیژن (O2%):"))
        self.lineEdit_28.setPlaceholderText(_translate("Form", "ex: 2%"))
        self.label_29.setText(_translate("Form", "گرم کن یک :"))
        self.label_30.setText(_translate("Form", "مشعل یک :"))
        self.label_19.setText(_translate("Form", "دمای دودکش (C°):"))
        self.lineEdit_19.setPlaceholderText(_translate("Form", "ex: 200 (°C)"))
        self.label_23.setText(_translate("Form", "درصد اکسیژن (O2%):"))
        self.lineEdit_22.setPlaceholderText(_translate("Form", "ex: 2%"))
        self.pushButton.setText(_translate("Form", "Cancel"))
        self.pushButton_2.setText(_translate("Form", "Ok"))
        self.radioButton_4.setText(_translate("Form", "مشعل دو "))
        self.label_25.setText(_translate("Form", "دمای دودکش (C°):"))
        self.lineEdit_27.setPlaceholderText(_translate("Form", "ex: 200 (°C)"))
        self.label_27.setText(_translate("Form", "درصد اکسیژن (O2%):"))
        self.lineEdit_25.setPlaceholderText(_translate("Form", "ex: 2%"))
        self.radioButton_2.setText(_translate("Form", "مشعل دو "))
        self.label_20.setText(_translate("Form", "دمای دودکش (C°):"))
        self.lineEdit_20.setPlaceholderText(_translate("Form", "ex: 200 (°C)"))
        self.label_24.setText(_translate("Form", "درصد اکسیژن (O2%):"))
        self.lineEdit_23.setPlaceholderText(_translate("Form", "ex: 2%"))

import svgfile_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

