# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MYAGA.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CityGateStation(object):
    def setupUi(self, CityGateStation):
        CityGateStation.setObjectName("CityGateStation")
        CityGateStation.resize(759, 514)
        CityGateStation.setToolTipDuration(-4)
        self.centralwidget = QtWidgets.QWidget(CityGateStation)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(2, 0, 751, 471))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 368, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.T1label = QtWidgets.QLabel(self.widget)
        self.T1label.setFrameShape(QtWidgets.QFrame.Panel)
        self.T1label.setObjectName("T1label")
        self.gridLayout_2.addWidget(self.T1label, 0, 2, 1, 1)
        self.P2label = QtWidgets.QLabel(self.widget)
        self.P2label.setFrameShape(QtWidgets.QFrame.Panel)
        self.P2label.setObjectName("P2label")
        self.gridLayout_2.addWidget(self.P2label, 0, 4, 1, 1)
        self.T2label = QtWidgets.QLabel(self.widget)
        self.T2label.setFrameShape(QtWidgets.QFrame.Panel)
        self.T2label.setObjectName("T2label")
        self.gridLayout_2.addWidget(self.T2label, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 3, 1, 1)
        self.T3label = QtWidgets.QLabel(self.widget)
        self.T3label.setFrameShape(QtWidgets.QFrame.Panel)
        self.T3label.setObjectName("T3label")
        self.gridLayout_2.addWidget(self.T3label, 0, 8, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 9, 1, 1)
        self.P1label = QtWidgets.QLabel(self.widget)
        self.P1label.setEnabled(True)
        self.P1label.setFrameShape(QtWidgets.QFrame.Panel)
        self.P1label.setTextFormat(QtCore.Qt.AutoText)
        self.P1label.setScaledContents(False)
        self.P1label.setObjectName("P1label")
        self.gridLayout_2.addWidget(self.P1label, 0, 1, 1, 1)
        self.P3label = QtWidgets.QLabel(self.widget)
        self.P3label.setFrameShape(QtWidgets.QFrame.Panel)
        self.P3label.setObjectName("P3label")
        self.gridLayout_2.addWidget(self.P3label, 0, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        CityGateStation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CityGateStation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        CityGateStation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CityGateStation)
        self.statusbar.setObjectName("statusbar")
        CityGateStation.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(CityGateStation)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(CityGateStation)
        self.actionExit.setObjectName("actionExit")
        self.actionGas_Configure = QtWidgets.QAction(CityGateStation)
        self.actionGas_Configure.setObjectName("actionGas_Configure")
        self.action_2 = QtWidgets.QAction(CityGateStation)
        self.action_2.setObjectName("action_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionGas_Configure)
        self.menuEdit.addAction(self.action_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(CityGateStation)
        QtCore.QMetaObject.connectSlotsByName(CityGateStation)

    def retranslateUi(self, CityGateStation):
        _translate = QtCore.QCoreApplication.translate
        CityGateStation.setWindowTitle(_translate("CityGateStation", "استگاه تقلیل فشار گاز"))
        self.T1label.setToolTip(_translate("CityGateStation", "<html><head/><body><p>دمای گاز ورودی به ایستگاه</p></body></html>"))
        self.T1label.setText(_translate("CityGateStation", "T1"))
        self.P2label.setToolTip(_translate("CityGateStation", "<html><head/><body><p>فشار گاز بعد از گرمکن</p></body></html>"))
        self.P2label.setText(_translate("CityGateStation", "P2"))
        self.T2label.setToolTip(_translate("CityGateStation", "<html><head/><body><p>دمای گاز بعد از گرمکن</p></body></html>"))
        self.T2label.setText(_translate("CityGateStation", "T2"))
        self.T3label.setToolTip(_translate("CityGateStation", "<html><head/><body><p>دمای گاز بعد از شیر فشار شکن</p></body></html>"))
        self.T3label.setText(_translate("CityGateStation", "T3"))
        self.P1label.setToolTip(_translate("CityGateStation", "<html><head/><body><p>فشار گاز ورودی به ایستگاه</p></body></html>"))
        self.P1label.setText(_translate("CityGateStation", "P1"))
        self.P3label.setToolTip(_translate("CityGateStation", "<html><head/><body><p>فشار گاز بعد از شیر فشار شکن</p></body></html>"))
        self.P3label.setText(_translate("CityGateStation", "P3"))
        self.menuFile.setTitle(_translate("CityGateStation", "File"))
        self.menuEdit.setTitle(_translate("CityGateStation", "Edit"))
        self.menuHelp.setTitle(_translate("CityGateStation", "Help"))
        self.actionOpen.setText(_translate("CityGateStation", "Open"))
        self.actionExit.setText(_translate("CityGateStation", "Exit"))
        self.actionGas_Configure.setText(_translate("CityGateStation", "Gas Configure"))
        self.action_2.setText(_translate("CityGateStation", "واحدها"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CityGateStation = QtWidgets.QMainWindow()
    ui = Ui_CityGateStation()
    ui.setupUi(CityGateStation)
    CityGateStation.show()
    sys.exit(app.exec_())

